before_script:
  - docker_login
  - export IMAGE_NAME=$(docker_image_name)

build_image:
  stage: build

  only:
    - /^master$/
    - /^development$/
    - /^(feature|release)\/.+$/
    - /^v\d+\.\d+\.\d+$/

  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
